import 'package:powersync/powersync.dart';

const powersyncAppSchema = Schema([
  Table('transactions', [
    Column.text('user_id'),
    Column.text('title'),
    Column.text('notes'),
    Column.real('amount'),
    Column.text('date'),
    Column.integer('type'),
    Column.text('category_id'),
    Column.integer('is_deleted'),
    Column.text('account_id'),
    Column.text('goal_id'),
    Column.integer('is_archived'),
  ]),
  Table('categories', [
    Column.text('user_id'),
    Column.text('name'),
    Column.real('balance'),
    Column.integer('reset_increment'),
    Column.integer('allow_negatives'),
    Column.integer('color'),
    Column.text('notes'),
    Column.integer('is_deleted'),
    Column.integer('is_archived'),
  ]),
  Table('accounts', [
    Column.text('user_id'),
    Column.text('name'),
    Column.integer('priority'),
    Column.integer('is_deleted'),
    Column.integer('is_archived'),
    Column.text('notes'),
    Column.integer('color'),
  ]),
  Table('goals', [
    Column.text('user_id'),
    Column.text('name'),
    Column.real('cost'),
    Column.text('due_date'),
    Column.integer('is_finished'),
    Column.integer('is_deleted'),
    Column.text('notes'),
    Column.integer('color'),
  ]),
]);
